apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::772706200515:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-eTdYWW31oVC9
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-dev
      userarn: arn:aws:iam::772706200515:user/sridhar
      username: sridhar
    - groups:
      - admin
      userarn: arn:aws:iam::772706200515:user/srividya
      username: srividya
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-16T05:27:16Z"
  name: aws-auth
  namespace: kube-system