apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::772706200515:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-eTdYWW31oVC9
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::111122223333:user/admin
      username: admin
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-16T05:27:16Z"
  name: aws-auth
  namespace: kube-system
  uid: 0cb4c191-5d3b-4d7f-8ed6-88eb825b63d8