apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::772706200515:role/eksctl-roboshop-dev-addon-iamserviceaccount-r-Role1-0eE3YpQuhR1L
  creationTimestamp: "2026-05-28T06:02:39Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: mongo-secret-reader
  namespace: roboshop
  resourceVersion: "10229"
  uid: 15eb3156-46b5-4ee2-8218-c9e861096442