apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: roboshop
spec:
  serviceAccount: mongo-secret-reader
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      # this command is given because there is no process running in side this aws-cli container
      command: ["sleep", "100000"]
